#!/bin/bash

lines=$(ls -lh $1 | wc -l)

if [ $# -ne 1 ]
then
    echo "this script requires exactly one directory path"
    echo "Please try again"
    exit
fi

echo "You have $(($lines-1)) objects in the $1 directory."

