#!/bin/bash

# Check to make sure the user has entered exactly two arguments.

if [ $# -ne 2 ]
then 
    echo "Usage: backups.sh <source_directory> <target_directory>"
    echo "Please try again"
    exit 1
fi 

# Check to see if rsync is installed 

if ! command -v rsync > /dev/null 2>&1
then 
    echo "This script requires rsync to be installed"
    echo "please install it"
    exit 2
fi
# sort like this  YYYY-MM-DD
current_date=$(date +%Y-%m-%d)

rsync_options="-avb --backup-dir $2/$current_date --delete "
$(which rsync) $rsync_options $1 $2/current >> backup_$current_date.log