name: Security Scan

on:
  push:
    branches:
      - main

jobs:
  run-dast-job:
    runs-on: ubuntu-latest

    env:
      DAST_TARGET_URL: 'https://www.temu.com/login.html?from=https%3A%2F%2Fwww.temu.com%2F-switch-oled-model-neon-blue-and-red-white--hk-version-only-with-hk-version-charger-g-601099518006684.html&login_scene=2&refer_page_name=goods&refer_page_id=10032_1701807081677_auah9i3yao&refer_page_sn=10032&_x_sessn_id=r4i0izt8ds&no_cache_id=8hp4m'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install wget
          sudo apt-get -y install wkhtmltopdf

      - name: Download and Extract ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Linux.tar.gz
          mkdir zap
          tar -xvf ZAP_2.11.1_Linux.tar.gz

      - name: Run DAST
        run: |
          cd ZAP_2.11.1
          ./zap.sh -cmd -quickurl $DAST_TARGET_URL -quickprogress -quickout ../zap_report.html
          cd ..

      - name: Convert HTML to PDF
        run: wkhtmltopdf zap_report.html zap_report.pdf

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: security-report
          path: zap_report.pdf
